# Exploracion inicial y vistazo al dataset

El objetivo de este notebook es entender que hay en el dataset a rasgos generales. Al terminar este notebook se busca saber el tamanio, el tipo de los datos y determinar si existen posibles alertas a las cuales prestarles atencion

### 1. Setup y carga

#### 1.1. Importar las librerias necesarias

In [7]:
import pandas as pd
import pathlib
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport

#### 1.2. Fijando RandomSeed

In [6]:
random_seed = 42

In [ ]:
ruta = pathlib.Path(r"E:\ROAD_TO_DATA_SCIENCE\proyectos_programacion\python\SALARYLENS\SalaryLens-Predictor-de-Retorno-Laboral-con-Machine-Learning\data\raw\job_salary_prediction_dataset.csv")

#comprobacion de carga del dataset
match ruta.exists(): 
    case True: 
        print("Dataset encontrado en la ruta correctamente correctamente, leyendo datos...")
        df = pd.read_csv(ruta)
        print("dataset guardado correctamente como df")
        display(df.head())
    case False:
        print("El dataset no ha sido encontrado en la ruta establecida")

Dataset encontrado en la ruta correctamente correctamente, leyendo datos...
dataset guardado correctamente como df

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

#### 1.3. Informacion basica del dataset

In [15]:
# Primeros 10 registros del dataset
df.head(10)

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069
5,AI Engineer,0,High School,4,Education,Enterprise,USA,No,2,180351
6,Backend Developer,6,High School,16,Manufacturing,Enterprise,Canada,No,3,165375
7,Machine Learning Engineer,4,Bachelor,18,Healthcare,Enterprise,Canada,Hybrid,5,202463
8,AI Engineer,5,Diploma,14,Telecom,Enterprise,Singapore,Yes,0,171834
9,Frontend Developer,18,PhD,2,Retail,Enterprise,India,Hybrid,5,128377

In [14]:
# Ultimos 5 registros del dataset
df.tail()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

In [17]:
df.sample(10)

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
133407,Product Manager,1,PhD,17,Government,Startup,Singapore,No,3,132867
79133,AI Engineer,20,High School,19,Finance,Startup,India,Yes,1,118197
1055,Product Manager,5,Diploma,19,Government,Small,Australia,Yes,1,130085
182821,Machine Learning Engineer,1,Bachelor,18,Technology,Medium,Remote,Hybrid,4,129504
78681,Frontend Developer,6,Bachelor,2,Healthcare,Medium,Sweden,Hybrid,5,97507
1620,Software Engineer,6,PhD,4,Manufacturing,Startup,Canada,No,5,144161
38282,Data Analyst,8,High School,18,Healthcare,Large,Germany,No,0,114417
11098,Cybersecurity Analyst,6,Diploma,17,Telecom,Startup,Remote,Yes,2,119272
121794,Machine Learning Engineer,0,PhD,2,Finance,Enterprise,India,No,4,118715
202724,Software Engineer,18,Diploma,2,Government,Medium,Canada,Yes,0,156478

### 2. Auditoria de estructura

#### 2.1. Identificar el tipo de datos de las columnas

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  object
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  object
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  object
 5   company_size      250000 non-null  object
 6   location          250000 non-null  object
 7   remote_work       250000 non-null  object
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), object(6)
memory usage: 19.1+ MB

Los tipos de datos son correctos.
- **Columnas numericas:** experience_years, skills_cout, certifications, salary
- **Columnas de texto:** job_title, education_level, industry, company_size, location, remote_work

#### 2.2. Documentar rangos anomalos

In [19]:
df.describe(include='all')

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
count,250000,250000.000000,250000,250000.000000,250000,250000,250000,250000,250000.000000,250000.000000
unique,12,NaN,5,NaN,10,5,10,3,NaN,NaN
top,Backend Developer,NaN,Master,NaN,Finance,Large,Australia,No,NaN,NaN
freq,21125,NaN,50352,NaN,25393,50254,25258,83621,NaN,NaN
mean,NaN,10.005408,NaN,9.997812,NaN,NaN,NaN,NaN,2.491928,145718.080524
std,NaN,6.060602,NaN,5.479288,NaN,NaN,NaN,NaN,1.706475,37407.952729
min,NaN,0.000000,NaN,1.000000,NaN,NaN,NaN,NaN,0.000000,31867.000000
25%,NaN,5.000000,NaN,5.000000,NaN,NaN,NaN,NaN,1.000000,119358.000000
50%,NaN,10.000000,NaN,10.000000,NaN,NaN,NaN,NaN,2.000000,143453.000000
75%,NaN,15.000000,NaN,15.000000,NaN,NaN,NaN,NaN,4.000000,169492.000000
max,NaN,20.000000,NaN,19.000000,NaN,NaN,NaN,NaN,5.000000,333046.000000

Revision:
- Todas las columnas cuentan con la misma cantidad de registros
- No se registran datos anomalos

### 3. Primera vista de tipos de datos

#### 3.1. Clasificacion manual

**Tipos de datos:**
- **job_title =** Variable cualitativa categorica
- **experience_years =** Variable cuantitativa discreta
- **education_level =** Variable cualitativa ordinal
- **skills_count =** Variable cuantitativa discreta
- **industry =** Cualitativa nominal
- **company_size =** Cualitativa ordinal
- **location =** Cualitava nominal
- **remote_work =** Cualitativa ordinal
- **certifications =** Cuantitativa discreta
- **salary =** Cuantitativa discreta

#### 3.2.